### ISSUE TITLE
Weitere Topics einpflegen

### ISSUE THREAD

**Issue by andreasteich** [andreasteich/ramory#4]

**Comment by andreasteich** [comment]
Nach weiteren Überlegungen würde ich vorschlagen, das issue zu schließen. Die Problematik mit Urheberrechtsthematiken und trademark Schutz ist fürchte ich nicht zu unterschätzen.

**Comment by dev-hias** [comment]
wieder aktuell ;)

**Comment by dev-hias** [comment]
extra Branch dafür wurde erstellt
